---
# GitHub Actions Workflow CI/CD
#

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          node --version
          echo "test stage"

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
          echo "build stage"

  deploy:
    name: deploy
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout our code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 Ls
        id: deploy
        run: |
          aws s3 ls
          ls
          echo "repo=${{ github.repository}},commitId=${{ github.sha }}"
