

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'
  # push:
  #   branches: [ '*' ]
  # pull_request:
  #   branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls
    - run: node --version

      # - name: Push to EC2
      #   id: deploy
      #   run: |
      #     # Assuming the Deployment Group is already setup
      #     aws deploy create-deployment \
      #       --application-name cookiecutter-django \
      #       --deployment-group-name deploy \
      #       --deployment-config-name CodeDeployDefault.OneAtATime \
      #       --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

